feat: HKISD-149 fetch SAP data based on earliest planning start year
City-of-Helsinki/infraohjelmointi-api pull request #161
Opened 2024-08-20 06:05 UTC by markspl

https://futurice.atlassian.net/browse/HKISD-149

Currently, SAP data is pulled from the past five years up to now. With this change, we check project planning year and use that for fetch the data.

If the SAP ID has multiple projects, the code checks earliest project plannin year and uses that.

2024-08-20 07:22 UTC, millaeerola reviewed
If planning start year isn't set, there shouldn't be any SAP data either (at least no need for showing it in the UI, since the project isn't shown in planning or coordinating views if planning start year and/or construction end year aren't set. So in that case there's no need to fetch any SAP data.

2024-09-03 07:09 UTC, millaeerola requested changes

2024-10-25 06:14 UTC, saijaseppa approved these changes

2024-10-25 07:01 UTC, millaeerola approved these changes

2024-10-25 07:01 UTC, merged