IO-172/171/168-Project-CRUD
City-of-Helsinki/infraohjelmointi-api pull request #4
Opened 2022-11-22 14:29 UTC by Git-Uzair

Implements CRUD functionality for all the Project and related information.
Implemented new Models, better serialization of data.
Written tests for Projects, Task and Budget item.
Solved migration issues

Overlaps with IO-172,171 & 168. All these tasks can be reviewed through this PR

2022-11-23 11:01 UTC, kgunga requested changes
We need also initial static data for dropdown menus like ProjectPhase, ProjectType. Please check other dropdown menus that need static data. Please populate database in a manner that description is in Finnish but its key is in english.

2022-11-23 11:35 UTC, Git-Uzair commented on infraohjelmointi_api/models/ProjectSet.py
> +    # finances = models.TextField(max_length=500, blank=True, null=True)
Yes, not sure if this field is Text or integer

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/models/ProjectSet.py
> +    # def sapProjects(self):
Removed

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/tests/test_Tasks.py
> +    TaskId = uuid.uuid4()
Created static UUID

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/tests/test_Tasks.py
> +            id=uuid.uuid4(), value="projectComplex"
Created static UUID

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/tests/test_Tasks.py
> +            id=uuid.uuid4(),
Created static UUID

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/tests/test_Tasks.py
> +            id=uuid.uuid4(),
Created static UUID

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/tests/test_Tasks.py
> +            sapProject=uuid.uuid4(),
Created static UUID

2022-11-24 11:34 UTC, Git-Uzair commented on infraohjelmointi_api/models/ProjectSet.py
> +    class ProjectPhaseChoices(models.TextChoices):
Made it a foreign key

2022-11-24 13:20 UTC, kgunga requested changes
Please remove all commented code and use static uuids in tests

2022-11-24 13:20 UTC, kgunga commented on infraohjelmointi_api/tests/test_Projects.py
> +            sapProject=[uuid.uuid4().__str__()],
static uuids, please

2022-11-24 13:20 UTC, kgunga commented on infraohjelmointi_api/tests/test_Projects.py
> +            sapProject=[uuid.uuid4().__str__()],
static uuids, please

2022-11-24 13:20 UTC, kgunga commented on infraohjelmointi_api/tests/test_Tasks.py
> +            sapProject=[uuid.uuid4().__str__()],
static uuids, please

2022-11-24 13:20 UTC, kgunga commented on infraohjelmointi_api/tests/test_Tasks.py
> +            sapNetwork=[uuid.uuid4().__str__()],
static uuids, please

2022-11-24 13:20 UTC, kgunga commented on infraohjelmointi_api/serializers.py
> +# class ProjectTypeValOnlySerializer(serializers.ModelSerializer):
remove commented code

2022-11-25 09:32 UTC, kgunga approved these changes
👍

2022-11-25 09:41 UTC, merged